# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

target 'SFDCOfflinePoc' do

source 'https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git' # need to be first 
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
pod 'SalesforceSDKCore'
pod 'SalesforceNetwork'
pod 'SalesforceRestAPI'
pod 'FMDB'
pod 'SmartStore'
pod 'SmartSync'
pod 'WYPopoverController'
pod 'MBProgressHUD', '~> 0.9.2'

end

